# Changes here will be overwritten by Copier
Authors: Stefan de Lange <langestefan@msn.com>
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Stefan de Lange
PackageName: OCPPData
PackageOwner: JuliaSolarPV
PackageUUID: 96fa3b67-1af3-5f07-99a6-8e4efc5edabb
StrategyConfirmIncluded: false
StrategyLevel: 3
StrategyReviewExcluded: false
_commit: v0.16.2
_src_path: /home/langestefan/dev/projects/2026/BestieTemplate.jl
